# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LldapCli < Formula
  desc "Lldap ts cli client"
  homepage "https://github.com/madeinoz67/lldap-cli"
  url "https://github.com/madeinoz67/lldap-cli/archive/refs/tags/v1.2.2.tar.gz"
  sha256 "95419e032a1e68837424583b47c3423906f568828015cd31c2121b2046b0bfaf"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "lldap-cli-darwin-arm64" => "lldap-cli"
  end

  test do
    assert_match "lldap-cli", shell_output("#{bin}/lldap-cli --version")
  end
end
