# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LldapCli < Formula
  desc "Lldap ts cli client"
  homepage "https://github.com/madeinoz67/lldap-cli"
  url "https://github.com/madeinoz67/lldap-cli/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "80e6ef013ac18764e0393c1506496534f09d8d51df7b083e4c3e68059f02122a"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "lldap-cli-darwin-arm64" => "lldap-cli"
  end

  test do
    assert_match "lldap-cli", shell_output("#{bin}/lldap-cli --version")
  end
end
