# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LldapCli < Formula
  desc "Lldap ts cli client"
  homepage "https://github.com/madeinoz67/lldap-cli"
  url "https://github.com/madeinoz67/lldap-cli/archive/refs/tags/v1.2.1.tar.gz"
  sha256 "df70143966a862e703652557ba1eea049c85d29598b20e16ef0fa81e0c28d981"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "lldap-cli-darwin-arm64" => "lldap-cli"
  end

  test do
    assert_match "lldap-cli", shell_output("#{bin}/lldap-cli --version")
  end
end
